export const Products = [
    {
        id:'1',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/men1.jpg',
        quantity:1,
        price:'$20.99',
        category:'male',
    },
    {
        id:'2',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/men2.jpg',
        quantity:1,
        price:'$20.99',
        category:'male',
    },
    {
        id:'3',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/men3.jpg',
        quantity:1,
        price:'$20.99',
        category:'male',
    },
    {
        id:'4',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/women1.jpg',
        quantity:1,
        price:'$20.99',
        category:'female',
    },
    {
        id:'5',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/women2.jpg',
        quantity:1,
        price:'$20.99',
        category:'female',
    },
    {
        id:'6',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/women3.jpg',
        quantity:1,
        price:'$20.99',
        category:'female',
    },
    {
        id:'7',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/child1.jpg',
        quantity:1,
        price:'$20.99',
        category:'child',
    },
    {
        id:'8',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/child2.jpg',
        quantity:1,
        price:'$20.99',
        category:'child',
    },
    {
        id:'9',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/ac1.jpg',
        quantity:1,
        price:'$20.99',
        category:'accessory',
    },
    {
        id:'10',
        name:'Pellentesque in ipsum id orci porta dapibus. Donec ',
        url:'/img/ac2.jpg',
        quantity:1,
        price:'$20.99',
        category:'accessory',
    },
]